In [1]:
!pip install openai

  Using cached distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
  Using cached sniffio-1.3.1-py3-none-any.whl.metadata (3.9 kB)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
   ---------------------------------------- 0.0/1.1 MB ? eta -:--:--
   ---------------------------------------- 1.1/1.1 MB 15.9 MB/s eta 0:00:00
Using cached distro-1.9.0-py3-none-any.whl (20 kB)
Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
   ---------------------------------------- 0.0/2.0 MB ? eta -:--:--
   ---------------------------------------- 2.0/2.0 MB 22.3 MB/s eta 0:00:00
Using cached sniffio-1.3.1-py3-none-any.whl (10 kB)
Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)



[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install sentence-transformers
!pip install scikit-learn


   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ------------ --------------------------- 3.1/9.7 MB 17.5 MB/s eta 0:00:01
   ---------------------- ----------------- 5.5/9.7 MB 13.6 MB/s eta 0:00:01
   --------------------------------- ------ 8.1/9.7 MB 12.9 MB/s eta 0:00:01
   ---------------------------------------- 9.7/9.7 MB 12.3 MB/s eta 0:00:00
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   --------- ------------------------------ 2.9/12.3 MB 14.4 MB/s eta 0:00:01
   ----------------- ---------------------- 5.5/12.3 MB 13.3 MB/s eta 0:00:01
   -------------------------- ------------- 8.1/12.3 MB 12.9 MB/s eta 0:00:01
   ---------------------------------- ----- 10.7/12.3 MB 12.8 MB/s eta 0:00:01
   ---------------------------------------- 12.3/12.3 MB 12.6 MB/s eta 0:00:00



[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


   ---------------------------------------- 0.0/8.1 MB ? eta -:--:--
   ------------------ --------------------- 3.7/8.1 MB 18.6 MB/s eta 0:00:01
   ------------------------------ --------- 6.3/8.1 MB 15.2 MB/s eta 0:00:01
   ---------------------------------------- 8.1/8.1 MB 14.1 MB/s eta 0:00:00
   ---------------------------------------- 0.0/2.3 MB ? eta -:--:--
   ---------------------------------------- 2.3/2.3 MB 12.1 MB/s eta 0:00:00
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ----------------- ---------------------- 3.1/7.0 MB 15.4 MB/s eta 0:00:01
   ----------------------------------- ---- 6.3/7.0 MB 15.1 MB/s eta 0:00:01
   ---------------------------------------- 7.0/7.0 MB 13.3 MB/s eta 0:00:00



[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
   ---------------------------------------- 0.0/553.3 kB ? eta -:--:--
   --------------------------------------- 553.3/553.3 kB 12.8 MB/s eta 0:00:00
   ---------------------------------------- 0.0/113.8 MB ? eta -:--:--
   - -------------------------------------- 3.9/113.8 MB 17.5 MB/s eta 0:00:07
   -- ------------------------------------- 6.6/113.8 MB 14.8 MB/s eta 0:00:08
   --- ------------------------------------ 8.9/113.8 MB 13.6 MB/s eta 0:00:08
   ---- ----------------------------------- 11.5/113.8 MB 13.3 MB/s eta 0:00:08
   ---- ----------------------------------- 14.2/113.8 MB 13.1 MB/s eta 0:00:08
   ----- ---------------------------------- 16.8/113.8 MB 13.0 MB/s eta 0:00:08
   ------ -------------------------------


[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip



[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [13]:
from sentence_transformers import SentenceTransformer


model = SentenceTransformer('all-MiniLM-L6-v2')

embeddings = model.encode(['This is a test sentence.', 'This is a test collections.'])
print(embeddings)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 432.29it/s, Materializing param=pooler.dense.weight]                             
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  | 
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


[[ 8.42964351e-02  5.79536557e-02  4.49332315e-03  1.05821095e-01
   7.08348723e-03 -1.78446732e-02 -1.68880727e-02 -1.52283330e-02
   4.04731296e-02  3.34225297e-02  1.04327641e-01 -4.70358171e-02
   6.88468339e-03  4.10179831e-02  1.87119357e-02 -4.14923020e-02
   2.36474779e-02 -5.65018021e-02 -3.36961932e-02  5.09909727e-02
   6.93032593e-02  5.47841974e-02 -9.78836231e-03  2.36971825e-02
   1.99965648e-02  9.71730705e-03 -5.88992015e-02  7.30746984e-03
   4.70264889e-02 -4.51012747e-03 -5.57996966e-02 -4.15942585e-03
   6.47570565e-02  4.80763055e-02  1.70208570e-02 -3.18338862e-03
   5.74023835e-02  3.52318697e-02 -5.88388043e-03  1.48328627e-02
   1.15762744e-02 -1.07480809e-01  1.91041995e-02  2.20857449e-02
   1.08645856e-02  3.78197595e-03 -3.19403857e-02  1.07277837e-02
  -4.84229159e-03 -2.83362865e-02 -5.25735728e-02 -7.05868825e-02
  -5.75557426e-02 -1.36328842e-02  5.68218483e-03  2.30746251e-02
   3.56977917e-02  1.49983931e-02  4.97427620e-02  4.26282957e-02
  -3.45888

In [23]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(embeddings)
print(similarity)

[[1.0000002 0.5227036]
 [0.5227036 0.9999999]]


In [20]:
docs = [
    "Python is a programming language",
    "Cats are animals",
    "AI is the future"
]

modelNew = SentenceTransformer('all-MiniLM-L6-v2')
embeddingsNew = modelNew.encode(docs)
print(len(embeddingsNew))
print(len(embeddingsNew[0]))

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 688.67it/s, Materializing param=pooler.dense.weight]                             
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  | 
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


3
384


In [21]:
print(cosine_similarity(embeddingsNew))

[[1.         0.20786092 0.25078171]
 [0.20786092 0.9999999  0.10266059]
 [0.25078171 0.10266059 1.0000002 ]]


In [24]:
query = "What is Python?"
query_embedding = modelNew.encode([query])
similarity_scores = cosine_similarity(query_embedding, embeddingsNew)
print(similarity_scores)

[[0.89221513 0.17555591 0.245454  ]]
